const tweetsData = [
  {
    name: "Deepak Sharma",
    username: "dasjideepak",
    date: "Sep 18",
    tweetText:
      "A program designed to help you develop full-stack web development skills and become job-ready",
    avatar:
      "https://avatars2.githubusercontent.com/u/38307844?s=460&u=f545a10c52359525a21efe75562a272f241ab57d&v=4",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/EfdQiz_UYAA4Zem?format=jpg&name=medium",
    replies: 12,
    retweets: 44,
    likes: 89,
  },
  {
    name: "Ankit Kumar",
    username: "nnnkit",
    date: "Sep 12",
    avatar:
      "https://avatars3.githubusercontent.com/u/3122626?s=460&u=541e00767a469b0faeedcac25f2b249ab104a9b0&v=4",
    tweetText:
      "JavaScript allows us to work with primitives (strings, numbers, etc.) as if they were objects. They also provide methods to call as such.",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "",
    replies: 3,
    retweets: 2,
    likes: 4,
  },
  {
    name: "Saurabh Gupta",
    username: "saurabhgupta26",
    date: "Sep 16",
    avatar:
      "https://avatars2.githubusercontent.com/u/56657029?s=460&u=ca2362423d0a438d8d048cc1c41f0997a68b7e89&v=4",
    tweetText:
      "Many built-in objects already exist, such as those that work with dates, errors, HTML elements, etc. They have different properties and methods.",
    hastags: [
      "frontend",
      "Coding",
      "100DaysOfCode",
      "hello",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/Eg4u4l0U8AATqOx?format=jpg&name=medium",
    replies: 14,
    retweets: 44,
    likes: 40,
  },
  {
    name: "Ankit Kumar",
    username: "nnnkit",
    date: "Sep 12",
    avatar:
      "https://avatars3.githubusercontent.com/u/3122626?s=460&u=541e00767a469b0faeedcac25f2b249ab104a9b0&v=4",
    tweetText:
      "JavaScript allows us to work with primitives (strings, numbers, etc.) as if they were objects. They also provide methods to call as such.",
    hastags: [],
    media: "",
    replies: 3,
    retweets: 2,
    likes: 4,
  },
  {
    name: "Deepak Sharma",
    username: "dasjideepak",
    date: "Sep 18",
    tweetText:
      "A program designed to help you develop full-stack web development skills and become job-ready",
    avatar:
      "https://avatars2.githubusercontent.com/u/38307844?s=460&u=f545a10c52359525a21efe75562a272f241ab57d&v=4",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/EfdQiz_UYAA4Zem?format=jpg&name=medium",
    replies: "",
    retweets: 3,
    likes: 23,
  },
  {
    name: "Karan Rathod",
    username: "karan-rathod-316",
    date: "Sep 18",
    tweetText:
      "A program designed to help you develop full-stack web development skills and become job-ready",
    avatar:
      "https://avatars3.githubusercontent.com/u/58169101?s=460&u=82a2eb28b799cc1d8fc3b6ef449f616e16707780&v=4",
    hastags: ["AltCampus", "100DaysOfCode", "Coding"],
    media: "",
    replies: 1,
    retweets: 4,
    likes: 12,
  },
  {
    name: "Abhishek Goswami",
    username: "abhigoswami12",
    date: "Sep 08",
    tweetText: "Started learning react ",
    avatar:
      "https://avatars1.githubusercontent.com/u/61133158?s=460&u=31211b9e980b9587459946fd4f72ec8ac1e422d8&v=4",
    hastags: ["frontend", "Coding", "100DaysOfCode"],
    media: "",
    replies: "",
    retweets: 44,
    likes: 89,
  },
  {
    name: "Deepak Sharma",
    username: "dasjideepak",
    date: "Sep 18",
    tweetText:
      "A program designed to help you develop full-stack web development skills and become job-ready",
    avatar:
      "https://avatars2.githubusercontent.com/u/38307844?s=460&u=f545a10c52359525a21efe75562a272f241ab57d&v=4",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/EfdQiz_UYAA4Zem?format=jpg&name=medium",
    replies: 12,
    retweets: 44,
    likes: 89,
  },
  {
    name: "Ankit Kumar",
    username: "nnnkit",
    date: "Sep 12",
    avatar:
      "https://avatars3.githubusercontent.com/u/3122626?s=460&u=541e00767a469b0faeedcac25f2b249ab104a9b0&v=4",
    tweetText:
      "JavaScript allows us to work with primitives (strings, numbers, etc.) as if they were objects. They also provide methods to call as such.",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "",
    replies: 3,
    retweets: 2,
    likes: 4,
  },
  {
    name: "Saurabh Gupta",
    username: "saurabhgupta26",
    date: "Sep 16",
    avatar:
      "https://avatars2.githubusercontent.com/u/56657029?s=460&u=ca2362423d0a438d8d048cc1c41f0997a68b7e89&v=4",
    tweetText:
      "Many built-in objects already exist, such as those that work with dates, errors, HTML elements, etc. They have different properties and methods.",
    hastags: [
      "frontend",
      "Coding",
      "100DaysOfCode",
      "hello",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/Eg4u4l0U8AATqOx?format=jpg&name=medium",
    replies: 14,
    retweets: 44,
    likes: 40,
  },
  {
    name: "Deepak Sharma",
    username: "dasjideepak",
    date: "Sep 18",
    tweetText:
      "A program designed to help you develop full-stack web development skills and become job-ready",
    avatar:
      "https://avatars2.githubusercontent.com/u/38307844?s=460&u=f545a10c52359525a21efe75562a272f241ab57d&v=4",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/EfdQiz_UYAA4Zem?format=jpg&name=medium",
    replies: 12,
    retweets: 44,
    likes: 89,
  },
  {
    name: "Ankit Kumar",
    username: "nnnkit",
    date: "Sep 12",
    avatar:
      "https://avatars3.githubusercontent.com/u/3122626?s=460&u=541e00767a469b0faeedcac25f2b249ab104a9b0&v=4",
    tweetText:
      "JavaScript allows us to work with primitives (strings, numbers, etc.) as if they were objects. They also provide methods to call as such.",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "",
    replies: 3,
    retweets: 2,
    likes: 4,
  },
  {
    name: "Saurabh Gupta",
    username: "saurabhgupta26",
    date: "Sep 16",
    avatar:
      "https://avatars2.githubusercontent.com/u/56657029?s=460&u=ca2362423d0a438d8d048cc1c41f0997a68b7e89&v=4",
    tweetText:
      "Many built-in objects already exist, such as those that work with dates, errors, HTML elements, etc. They have different properties and methods.",
    hastags: [
      "frontend",
      "Coding",
      "100DaysOfCode",
      "hello",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/Eg4u4l0U8AATqOx?format=jpg&name=medium",
    replies: 14,
    retweets: 44,
    likes: 40,
  },

  {
    name: "Deepak Sharma",
    username: "dasjideepak",
    date: "Sep 18",
    tweetText:
      "A program designed to help you develop full-stack web development skills and become job-ready",
    avatar:
      "https://avatars2.githubusercontent.com/u/38307844?s=460&u=f545a10c52359525a21efe75562a272f241ab57d&v=4",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/EfdQiz_UYAA4Zem?format=jpg&name=medium",
    replies: 12,
    retweets: 44,
    likes: 89,
  },
  {
    name: "Ankit Kumar",
    username: "nnnkit",
    date: "Sep 12",
    avatar:
      "https://avatars3.githubusercontent.com/u/3122626?s=460&u=541e00767a469b0faeedcac25f2b249ab104a9b0&v=4",
    tweetText:
      "JavaScript allows us to work with primitives (strings, numbers, etc.) as if they were objects. They also provide methods to call as such.",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "",
    replies: 3,
    retweets: 2,
    likes: 4,
  },
  {
    name: "Saurabh Gupta",
    username: "saurabhgupta26",
    date: "Sep 16",
    avatar:
      "https://avatars2.githubusercontent.com/u/56657029?s=460&u=ca2362423d0a438d8d048cc1c41f0997a68b7e89&v=4",
    tweetText:
      "Many built-in objects already exist, such as those that work with dates, errors, HTML elements, etc. They have different properties and methods.",
    hastags: [
      "frontend",
      "Coding",
      "100DaysOfCode",
      "hello",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/Eg4u4l0U8AATqOx?format=jpg&name=medium",
    replies: 14,
    retweets: 44,
    likes: 40,
  },

  {
    name: "Deepak Sharma",
    username: "dasjideepak",
    date: "Sep 18",
    tweetText:
      "A program designed to help you develop full-stack web development skills and become job-ready",
    avatar:
      "https://avatars2.githubusercontent.com/u/38307844?s=460&u=f545a10c52359525a21efe75562a272f241ab57d&v=4",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/EfdQiz_UYAA4Zem?format=jpg&name=medium",
    replies: 12,
    retweets: 44,
    likes: 89,
  },
  {
    name: "Ankit Kumar",
    username: "nnnkit",
    date: "Sep 12",
    avatar:
      "https://avatars3.githubusercontent.com/u/3122626?s=460&u=541e00767a469b0faeedcac25f2b249ab104a9b0&v=4",
    tweetText:
      "JavaScript allows us to work with primitives (strings, numbers, etc.) as if they were objects. They also provide methods to call as such.",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "",
    replies: 3,
    retweets: 2,
    likes: 4,
  },
  {
    name: "Saurabh Gupta",
    username: "saurabhgupta26",
    date: "Sep 16",
    avatar:
      "https://avatars2.githubusercontent.com/u/56657029?s=460&u=ca2362423d0a438d8d048cc1c41f0997a68b7e89&v=4",
    tweetText:
      "Many built-in objects already exist, such as those that work with dates, errors, HTML elements, etc. They have different properties and methods.",
    hastags: [
      "frontend",
      "Coding",
      "100DaysOfCode",
      "hello",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/Eg4u4l0U8AATqOx?format=jpg&name=medium",
    replies: 14,
    retweets: 44,
    likes: 40,
  },
  {
    name: "Deepak Sharma",
    username: "dasjideepak",
    date: "Sep 18",
    tweetText:
      "A program designed to help you develop full-stack web development skills and become job-ready",
    avatar:
      "https://avatars2.githubusercontent.com/u/38307844?s=460&u=f545a10c52359525a21efe75562a272f241ab57d&v=4",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/EfdQiz_UYAA4Zem?format=jpg&name=medium",
    replies: 12,
    retweets: 44,
    likes: 89,
  },
  {
    name: "Ankit Kumar",
    username: "nnnkit",
    date: "Sep 12",
    avatar:
      "https://avatars3.githubusercontent.com/u/3122626?s=460&u=541e00767a469b0faeedcac25f2b249ab104a9b0&v=4",
    tweetText:
      "JavaScript allows us to work with primitives (strings, numbers, etc.) as if they were objects. They also provide methods to call as such.",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "",
    replies: 3,
    retweets: 2,
    likes: 4,
  },
  {
    name: "Saurabh Gupta",
    username: "saurabhgupta26",
    date: "Sep 16",
    avatar:
      "https://avatars2.githubusercontent.com/u/56657029?s=460&u=ca2362423d0a438d8d048cc1c41f0997a68b7e89&v=4",
    tweetText:
      "Many built-in objects already exist, such as those that work with dates, errors, HTML elements, etc. They have different properties and methods.",
    hastags: [
      "frontend",
      "Coding",
      "100DaysOfCode",
      "hello",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/Eg4u4l0U8AATqOx?format=jpg&name=medium",
    replies: 14,
    retweets: 44,
    likes: 40,
  },
  {
    name: "Deepak Sharma",
    username: "dasjideepak",
    date: "Sep 18",
    tweetText:
      "A program designed to help you develop full-stack web development skills and become job-ready",
    avatar:
      "https://avatars2.githubusercontent.com/u/38307844?s=460&u=f545a10c52359525a21efe75562a272f241ab57d&v=4",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/EfdQiz_UYAA4Zem?format=jpg&name=medium",
    replies: 12,
    retweets: 44,
    likes: 89,
  },
  {
    name: "Ankit Kumar",
    username: "nnnkit",
    date: "Sep 12",
    avatar:
      "https://avatars3.githubusercontent.com/u/3122626?s=460&u=541e00767a469b0faeedcac25f2b249ab104a9b0&v=4",
    tweetText:
      "JavaScript allows us to work with primitives (strings, numbers, etc.) as if they were objects. They also provide methods to call as such.",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "",
    replies: 3,
    retweets: 2,
    likes: 4,
  },
  {
    name: "Saurabh Gupta",
    username: "saurabhgupta26",
    date: "Sep 16",
    avatar:
      "https://avatars2.githubusercontent.com/u/56657029?s=460&u=ca2362423d0a438d8d048cc1c41f0997a68b7e89&v=4",
    tweetText:
      "Many built-in objects already exist, such as those that work with dates, errors, HTML elements, etc. They have different properties and methods.",
    hastags: [
      "frontend",
      "Coding",
      "100DaysOfCode",
      "hello",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/Eg4u4l0U8AATqOx?format=jpg&name=medium",
    replies: 14,
    retweets: 44,
    likes: 40,
  },
  {
    name: "Deepak Sharma",
    username: "dasjideepak",
    date: "Sep 18",
    tweetText:
      "A program designed to help you develop full-stack web development skills and become job-ready",
    avatar:
      "https://avatars2.githubusercontent.com/u/38307844?s=460&u=f545a10c52359525a21efe75562a272f241ab57d&v=4",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/EfdQiz_UYAA4Zem?format=jpg&name=medium",
    replies: 12,
    retweets: 44,
    likes: 89,
  },
  {
    name: "Ankit Kumar",
    username: "nnnkit",
    date: "Sep 12",
    avatar:
      "https://avatars3.githubusercontent.com/u/3122626?s=460&u=541e00767a469b0faeedcac25f2b249ab104a9b0&v=4",
    tweetText:
      "JavaScript allows us to work with primitives (strings, numbers, etc.) as if they were objects. They also provide methods to call as such.",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "",
    replies: 3,
    retweets: 2,
    likes: 4,
  },
  {
    name: "Saurabh Gupta",
    username: "saurabhgupta26",
    date: "Sep 16",
    avatar:
      "https://avatars2.githubusercontent.com/u/56657029?s=460&u=ca2362423d0a438d8d048cc1c41f0997a68b7e89&v=4",
    tweetText:
      "Many built-in objects already exist, such as those that work with dates, errors, HTML elements, etc. They have different properties and methods.",
    hastags: [
      "frontend",
      "Coding",
      "100DaysOfCode",
      "hello",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/Eg4u4l0U8AATqOx?format=jpg&name=medium",
    replies: 14,
    retweets: 44,
    likes: 40,
  },
  {
    name: "Deepak Sharma",
    username: "dasjideepak",
    date: "Sep 18",
    tweetText:
      "A program designed to help you develop full-stack web development skills and become job-ready",
    avatar:
      "https://avatars2.githubusercontent.com/u/38307844?s=460&u=f545a10c52359525a21efe75562a272f241ab57d&v=4",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/EfdQiz_UYAA4Zem?format=jpg&name=medium",
    replies: 12,
    retweets: 44,
    likes: 89,
  },
  {
    name: "Ankit Kumar",
    username: "nnnkit",
    date: "Sep 12",
    avatar:
      "https://avatars3.githubusercontent.com/u/3122626?s=460&u=541e00767a469b0faeedcac25f2b249ab104a9b0&v=4",
    tweetText:
      "JavaScript allows us to work with primitives (strings, numbers, etc.) as if they were objects. They also provide methods to call as such.",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "",
    replies: 3,
    retweets: 2,
    likes: 4,
  },
  {
    name: "Saurabh Gupta",
    username: "saurabhgupta26",
    date: "Sep 16",
    avatar:
      "https://avatars2.githubusercontent.com/u/56657029?s=460&u=ca2362423d0a438d8d048cc1c41f0997a68b7e89&v=4",
    tweetText:
      "Many built-in objects already exist, such as those that work with dates, errors, HTML elements, etc. They have different properties and methods.",
    hastags: [
      "frontend",
      "Coding",
      "100DaysOfCode",
      "hello",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/Eg4u4l0U8AATqOx?format=jpg&name=medium",
    replies: 14,
    retweets: 44,
    likes: 40,
  },
  {
    name: "Deepak Sharma",
    username: "dasjideepak",
    date: "Sep 18",
    tweetText:
      "A program designed to help you develop full-stack web development skills and become job-ready",
    avatar:
      "https://avatars2.githubusercontent.com/u/38307844?s=460&u=f545a10c52359525a21efe75562a272f241ab57d&v=4",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/EfdQiz_UYAA4Zem?format=jpg&name=medium",
    replies: 12,
    retweets: 44,
    likes: 89,
  },
  {
    name: "Ankit Kumar",
    username: "nnnkit",
    date: "Sep 12",
    avatar:
      "https://avatars3.githubusercontent.com/u/3122626?s=460&u=541e00767a469b0faeedcac25f2b249ab104a9b0&v=4",
    tweetText:
      "JavaScript allows us to work with primitives (strings, numbers, etc.) as if they were objects. They also provide methods to call as such.",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "",
    replies: 3,
    retweets: 2,
    likes: 4,
  },
  {
    name: "Saurabh Gupta",
    username: "saurabhgupta26",
    date: "Sep 16",
    avatar:
      "https://avatars2.githubusercontent.com/u/56657029?s=460&u=ca2362423d0a438d8d048cc1c41f0997a68b7e89&v=4",
    tweetText:
      "Many built-in objects already exist, such as those that work with dates, errors, HTML elements, etc. They have different properties and methods.",
    hastags: [
      "frontend",
      "Coding",
      "100DaysOfCode",
      "hello",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/Eg4u4l0U8AATqOx?format=jpg&name=medium",
    replies: 14,
    retweets: 44,
    likes: 40,
  },
  {
    name: "Deepak Sharma",
    username: "dasjideepak",
    date: "Sep 18",
    tweetText:
      "A program designed to help you develop full-stack web development skills and become job-ready",
    avatar:
      "https://avatars2.githubusercontent.com/u/38307844?s=460&u=f545a10c52359525a21efe75562a272f241ab57d&v=4",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/EfdQiz_UYAA4Zem?format=jpg&name=medium",
    replies: 12,
    retweets: 44,
    likes: 89,
  },
  {
    name: "Ankit Kumar",
    username: "nnnkit",
    date: "Sep 12",
    avatar:
      "https://avatars3.githubusercontent.com/u/3122626?s=460&u=541e00767a469b0faeedcac25f2b249ab104a9b0&v=4",
    tweetText:
      "JavaScript allows us to work with primitives (strings, numbers, etc.) as if they were objects. They also provide methods to call as such.",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "",
    replies: 3,
    retweets: 2,
    likes: 4,
  },
  {
    name: "Saurabh Gupta",
    username: "saurabhgupta26",
    date: "Sep 16",
    avatar:
      "https://avatars2.githubusercontent.com/u/56657029?s=460&u=ca2362423d0a438d8d048cc1c41f0997a68b7e89&v=4",
    tweetText:
      "Many built-in objects already exist, such as those that work with dates, errors, HTML elements, etc. They have different properties and methods.",
    hastags: [
      "frontend",
      "Coding",
      "100DaysOfCode",
      "hello",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/Eg4u4l0U8AATqOx?format=jpg&name=medium",
    replies: 14,
    retweets: 44,
    likes: 40,
  },
  {
    name: "Deepak Sharma",
    username: "dasjideepak",
    date: "Sep 18",
    tweetText:
      "A program designed to help you develop full-stack web development skills and become job-ready",
    avatar:
      "https://avatars2.githubusercontent.com/u/38307844?s=460&u=f545a10c52359525a21efe75562a272f241ab57d&v=4",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/EfdQiz_UYAA4Zem?format=jpg&name=medium",
    replies: 12,
    retweets: 44,
    likes: 89,
  },
  {
    name: "Ankit Kumar",
    username: "nnnkit",
    date: "Sep 12",
    avatar:
      "https://avatars3.githubusercontent.com/u/3122626?s=460&u=541e00767a469b0faeedcac25f2b249ab104a9b0&v=4",
    tweetText:
      "JavaScript allows us to work with primitives (strings, numbers, etc.) as if they were objects. They also provide methods to call as such.",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "",
    replies: 3,
    retweets: 2,
    likes: 4,
  },
  {
    name: "Saurabh Gupta",
    username: "saurabhgupta26",
    date: "Sep 16",
    avatar:
      "https://avatars2.githubusercontent.com/u/56657029?s=460&u=ca2362423d0a438d8d048cc1c41f0997a68b7e89&v=4",
    tweetText:
      "Many built-in objects already exist, such as those that work with dates, errors, HTML elements, etc. They have different properties and methods.",
    hastags: [
      "frontend",
      "Coding",
      "100DaysOfCode",
      "hello",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/Eg4u4l0U8AATqOx?format=jpg&name=medium",
    replies: 14,
    retweets: 44,
    likes: 40,
  },
  {
    name: "Deepak Sharma",
    username: "dasjideepak",
    date: "Sep 18",
    tweetText:
      "A program designed to help you develop full-stack web development skills and become job-ready",
    avatar:
      "https://avatars2.githubusercontent.com/u/38307844?s=460&u=f545a10c52359525a21efe75562a272f241ab57d&v=4",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/EfdQiz_UYAA4Zem?format=jpg&name=medium",
    replies: 12,
    retweets: 44,
    likes: 89,
  },
  {
    name: "Ankit Kumar",
    username: "nnnkit",
    date: "Sep 12",
    avatar:
      "https://avatars3.githubusercontent.com/u/3122626?s=460&u=541e00767a469b0faeedcac25f2b249ab104a9b0&v=4",
    tweetText:
      "JavaScript allows us to work with primitives (strings, numbers, etc.) as if they were objects. They also provide methods to call as such.",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "",
    replies: 3,
    retweets: 2,
    likes: 4,
  },
  {
    name: "Saurabh Gupta",
    username: "saurabhgupta26",
    date: "Sep 16",
    avatar:
      "https://avatars2.githubusercontent.com/u/56657029?s=460&u=ca2362423d0a438d8d048cc1c41f0997a68b7e89&v=4",
    tweetText:
      "Many built-in objects already exist, such as those that work with dates, errors, HTML elements, etc. They have different properties and methods.",
    hastags: [
      "frontend",
      "Coding",
      "100DaysOfCode",
      "hello",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/Eg4u4l0U8AATqOx?format=jpg&name=medium",
    replies: 14,
    retweets: 44,
    likes: 40,
  },
  {
    name: "Deepak Sharma",
    username: "dasjideepak",
    date: "Sep 18",
    tweetText:
      "A program designed to help you develop full-stack web development skills and become job-ready",
    avatar:
      "https://avatars2.githubusercontent.com/u/38307844?s=460&u=f545a10c52359525a21efe75562a272f241ab57d&v=4",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/EfdQiz_UYAA4Zem?format=jpg&name=medium",
    replies: 12,
    retweets: 44,
    likes: 89,
  },
  {
    name: "Ankit Kumar",
    username: "nnnkit",
    date: "Sep 12",
    avatar:
      "https://avatars3.githubusercontent.com/u/3122626?s=460&u=541e00767a469b0faeedcac25f2b249ab104a9b0&v=4",
    tweetText:
      "JavaScript allows us to work with primitives (strings, numbers, etc.) as if they were objects. They also provide methods to call as such.",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "",
    replies: 3,
    retweets: 2,
    likes: 4,
  },
  {
    name: "Saurabh Gupta",
    username: "saurabhgupta26",
    date: "Sep 16",
    avatar:
      "https://avatars2.githubusercontent.com/u/56657029?s=460&u=ca2362423d0a438d8d048cc1c41f0997a68b7e89&v=4",
    tweetText:
      "Many built-in objects already exist, such as those that work with dates, errors, HTML elements, etc. They have different properties and methods.",
    hastags: [
      "frontend",
      "Coding",
      "100DaysOfCode",
      "hello",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/Eg4u4l0U8AATqOx?format=jpg&name=medium",
    replies: 14,
    retweets: 44,
    likes: 40,
  },
  {
    name: "Deepak Sharma",
    username: "dasjideepak",
    date: "Sep 18",
    tweetText:
      "A program designed to help you develop full-stack web development skills and become job-ready",
    avatar:
      "https://avatars2.githubusercontent.com/u/38307844?s=460&u=f545a10c52359525a21efe75562a272f241ab57d&v=4",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/EfdQiz_UYAA4Zem?format=jpg&name=medium",
    replies: 12,
    retweets: 44,
    likes: 89,
  },
  {
    name: "Ankit Kumar",
    username: "nnnkit",
    date: "Sep 12",
    avatar:
      "https://avatars3.githubusercontent.com/u/3122626?s=460&u=541e00767a469b0faeedcac25f2b249ab104a9b0&v=4",
    tweetText:
      "JavaScript allows us to work with primitives (strings, numbers, etc.) as if they were objects. They also provide methods to call as such.",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "",
    replies: 3,
    retweets: 2,
    likes: 4,
  },
  {
    name: "Saurabh Gupta",
    username: "saurabhgupta26",
    date: "Sep 16",
    avatar:
      "https://avatars2.githubusercontent.com/u/56657029?s=460&u=ca2362423d0a438d8d048cc1c41f0997a68b7e89&v=4",
    tweetText:
      "Many built-in objects already exist, such as those that work with dates, errors, HTML elements, etc. They have different properties and methods.",
    hastags: [
      "frontend",
      "Coding",
      "100DaysOfCode",
      "hello",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/Eg4u4l0U8AATqOx?format=jpg&name=medium",
    replies: 14,
    retweets: 44,
    likes: 40,
  },
  {
    name: "Deepak Sharma",
    username: "dasjideepak",
    date: "Sep 18",
    tweetText:
      "A program designed to help you develop full-stack web development skills and become job-ready",
    avatar:
      "https://avatars2.githubusercontent.com/u/38307844?s=460&u=f545a10c52359525a21efe75562a272f241ab57d&v=4",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/EfdQiz_UYAA4Zem?format=jpg&name=medium",
    replies: 12,
    retweets: 44,
    likes: 89,
  },
  {
    name: "Ankit Kumar",
    username: "nnnkit",
    date: "Sep 12",
    avatar:
      "https://avatars3.githubusercontent.com/u/3122626?s=460&u=541e00767a469b0faeedcac25f2b249ab104a9b0&v=4",
    tweetText:
      "JavaScript allows us to work with primitives (strings, numbers, etc.) as if they were objects. They also provide methods to call as such.",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "",
    replies: 3,
    retweets: 2,
    likes: 4,
  },
  {
    name: "Saurabh Gupta",
    username: "saurabhgupta26",
    date: "Sep 16",
    avatar:
      "https://avatars2.githubusercontent.com/u/56657029?s=460&u=ca2362423d0a438d8d048cc1c41f0997a68b7e89&v=4",
    tweetText:
      "Many built-in objects already exist, such as those that work with dates, errors, HTML elements, etc. They have different properties and methods.",
    hastags: [
      "frontend",
      "Coding",
      "100DaysOfCode",
      "hello",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/Eg4u4l0U8AATqOx?format=jpg&name=medium",
    replies: 14,
    retweets: 44,
    likes: 40,
  },
  {
    name: "Deepak Sharma",
    username: "dasjideepak",
    date: "Sep 18",
    tweetText:
      "A program designed to help you develop full-stack web development skills and become job-ready",
    avatar:
      "https://avatars2.githubusercontent.com/u/38307844?s=460&u=f545a10c52359525a21efe75562a272f241ab57d&v=4",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/EfdQiz_UYAA4Zem?format=jpg&name=medium",
    replies: 12,
    retweets: 44,
    likes: 89,
  },
  {
    name: "Ankit Kumar",
    username: "nnnkit",
    date: "Sep 12",
    avatar:
      "https://avatars3.githubusercontent.com/u/3122626?s=460&u=541e00767a469b0faeedcac25f2b249ab104a9b0&v=4",
    tweetText:
      "JavaScript allows us to work with primitives (strings, numbers, etc.) as if they were objects. They also provide methods to call as such.",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "",
    replies: 3,
    retweets: 2,
    likes: 4,
  },
  {
    name: "Saurabh Gupta",
    username: "saurabhgupta26",
    date: "Sep 16",
    avatar:
      "https://avatars2.githubusercontent.com/u/56657029?s=460&u=ca2362423d0a438d8d048cc1c41f0997a68b7e89&v=4",
    tweetText:
      "Many built-in objects already exist, such as those that work with dates, errors, HTML elements, etc. They have different properties and methods.",
    hastags: [
      "frontend",
      "Coding",
      "100DaysOfCode",
      "hello",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/Eg4u4l0U8AATqOx?format=jpg&name=medium",
    replies: 14,
    retweets: 44,
    likes: 40,
  },
  {
    name: "Deepak Sharma",
    username: "dasjideepak",
    date: "Sep 18",
    tweetText:
      "A program designed to help you develop full-stack web development skills and become job-ready",
    avatar:
      "https://avatars2.githubusercontent.com/u/38307844?s=460&u=f545a10c52359525a21efe75562a272f241ab57d&v=4",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/EfdQiz_UYAA4Zem?format=jpg&name=medium",
    replies: 12,
    retweets: 44,
    likes: 89,
  },
  {
    name: "Ankit Kumar",
    username: "nnnkit",
    date: "Sep 12",
    avatar:
      "https://avatars3.githubusercontent.com/u/3122626?s=460&u=541e00767a469b0faeedcac25f2b249ab104a9b0&v=4",
    tweetText:
      "JavaScript allows us to work with primitives (strings, numbers, etc.) as if they were objects. They also provide methods to call as such.",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "",
    replies: 3,
    retweets: 2,
    likes: 4,
  },
  {
    name: "Saurabh Gupta",
    username: "saurabhgupta26",
    date: "Sep 16",
    avatar:
      "https://avatars2.githubusercontent.com/u/56657029?s=460&u=ca2362423d0a438d8d048cc1c41f0997a68b7e89&v=4",
    tweetText:
      "Many built-in objects already exist, such as those that work with dates, errors, HTML elements, etc. They have different properties and methods.",
    hastags: [
      "frontend",
      "Coding",
      "100DaysOfCode",
      "hello",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/Eg4u4l0U8AATqOx?format=jpg&name=medium",
    replies: 14,
    retweets: 44,
    likes: 40,
  },
  {
    name: "Deepak Sharma",
    username: "dasjideepak",
    date: "Sep 18",
    tweetText:
      "A program designed to help you develop full-stack web development skills and become job-ready",
    avatar:
      "https://avatars2.githubusercontent.com/u/38307844?s=460&u=f545a10c52359525a21efe75562a272f241ab57d&v=4",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/EfdQiz_UYAA4Zem?format=jpg&name=medium",
    replies: 12,
    retweets: 44,
    likes: 89,
  },
  {
    name: "Ankit Kumar",
    username: "nnnkit",
    date: "Sep 12",
    avatar:
      "https://avatars3.githubusercontent.com/u/3122626?s=460&u=541e00767a469b0faeedcac25f2b249ab104a9b0&v=4",
    tweetText:
      "JavaScript allows us to work with primitives (strings, numbers, etc.) as if they were objects. They also provide methods to call as such.",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "",
    replies: 3,
    retweets: 2,
    likes: 4,
  },
  {
    name: "Saurabh Gupta",
    username: "saurabhgupta26",
    date: "Sep 16",
    avatar:
      "https://avatars2.githubusercontent.com/u/56657029?s=460&u=ca2362423d0a438d8d048cc1c41f0997a68b7e89&v=4",
    tweetText:
      "Many built-in objects already exist, such as those that work with dates, errors, HTML elements, etc. They have different properties and methods.",
    hastags: [
      "frontend",
      "Coding",
      "100DaysOfCode",
      "hello",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/Eg4u4l0U8AATqOx?format=jpg&name=medium",
    replies: 14,
    retweets: 44,
    likes: 40,
  },
  {
    name: "Deepak Sharma",
    username: "dasjideepak",
    date: "Sep 18",
    tweetText:
      "A program designed to help you develop full-stack web development skills and become job-ready",
    avatar:
      "https://avatars2.githubusercontent.com/u/38307844?s=460&u=f545a10c52359525a21efe75562a272f241ab57d&v=4",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/EfdQiz_UYAA4Zem?format=jpg&name=medium",
    replies: 12,
    retweets: 44,
    likes: 89,
  },
  {
    name: "Ankit Kumar",
    username: "nnnkit",
    date: "Sep 12",
    avatar:
      "https://avatars3.githubusercontent.com/u/3122626?s=460&u=541e00767a469b0faeedcac25f2b249ab104a9b0&v=4",
    tweetText:
      "JavaScript allows us to work with primitives (strings, numbers, etc.) as if they were objects. They also provide methods to call as such.",
    hastags: [
      "javascript",
      "altcampus",
      "webdev",
      "frontend",
      "Coding",
      "100DaysOfCode",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "",
    replies: 3,
    retweets: 2,
    likes: 4,
  },
  {
    name: "Saurabh Gupta",
    username: "saurabhgupta26",
    date: "Sep 16",
    avatar:
      "https://avatars2.githubusercontent.com/u/56657029?s=460&u=ca2362423d0a438d8d048cc1c41f0997a68b7e89&v=4",
    tweetText:
      "Many built-in objects already exist, such as those that work with dates, errors, HTML elements, etc. They have different properties and methods.",
    hastags: [
      "frontend",
      "Coding",
      "100DaysOfCode",
      "hello",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "altcampus",
      "deepak",
      "frontend",
      "Coding",
      "100DaysOfCode",
    ],
    media: "https://pbs.twimg.com/media/Eg4u4l0U8AATqOx?format=jpg&name=medium",
    replies: 14,
    retweets: 44,
    likes: 40,
  },
];

export default tweetsData;
